### PR TITLE
Adding Local Deployment

### PR DESCRIPTION
**Pull request by emanuele-leopardi**
This PR introduces the following:
- Dockefile to be able to run the code inside a container
- Helm Chart , that enables to deploy the container inside kubernetes
- Update to Readme.md file to be able to install tools to run a local k8s cluster 
- Tiltfile to be able to deploy ( through the use of setup.sh script) the dockerized code in a local k8s cluster.

### CODE REVIEW

**Comment by r4m** [comment]
Hi @emanuele-leopardi thanks for the contribution! I saw your files and I was wondering: to not mess up with the main folder, can you group all your files within a subfolder, e.g. called `k8s`? 
Ideally we can have a folder in the root called `local`, in which we can collect any other material related to local installation. Inside it you can put your `k8s` one with all the files you added.
Let me know what you think.

**Comment by emanuele-leopardi** [comment]
sure no problem, I'll update the PR with the new folder structure.

**Comment by emanuele-leopardi** [comment]
Mmm... I thought I could but in reality I have dependencies with the positioning of the code:
- `Dockerfile` needs to be in the root dir as that becomes the build context for building the container itself.
- `Tiltfile` has a task that executes the building process so for the same reason needs to be in the root folder where `Dockerfile` lives.
- `openaccessgpt` is a Helm Chart , it can be used for local deployment but also for deployment in any other kubernetes-based environment, so it doesn't really make sense to put it inside a `local` folder. If you wish I can move it into a `chart` folder
- `setup.sh` is bounded to the `Tiltfile` location
- `module` contains library functions for `Tiltfile` but at this point it doesn't give any organizational advantage to put it into a different folder ( even if in this case it is possible)

**Comment by r4m** [comment]
Hey @emanuele-leopardi thanks for the clarifications, I was thinking about this alternative that I'd like having you thinking about in terms of feasibility.

1. put the `k8s` files in the subfolder as stated above
2. edit the `package.json` to add a script cmd that will invoke the setup of the app folder for a specific `local` config and also have another command to execute the local run 
```json
{
    "scripts": {
        "local-setup": "node local/setup.js",
       "local-run": "node local/run.js"
    }
}
```
3. inside the `local` folder we put the `setup.js` file that contains the following
```javascript
const { exec } = require('node:child_process')
switch (process.argv[0]) {
  case 'k8s':
    console.log('Put here all the commands, for Win and MacOS that will copy the files in the root folder and execute any other operation needed to correctly configure the env for running .');
   // e.g. the command below is used to move the Dockerfile in the root folder
   const command = exec("cp local/k8s/Dockerfile .");
    break;
  case 'whatever':
    break;
  default:
    console.log(`Sorry, local config for ${process.argv[0]} not supported.`);
}
```
what happens here is that for example you will write the commands for moving the files you need within the root folder.
4. inside the `local` folder we put the `run.js` file that contains basically the switch statement as per the other script, but the code executed is the one of your `setup.sh` (ideally this one for Win and MacOS too).
5. Update te README accordingly to explain the main commands `local-setup` and `local-run` and to list all the different type of modalities supported (e.g. `k8s`)
6. User configures the local env running the command `npm run local-setup k8s` only once.
7. User starts the local instance running the command  `npm run local-run k8s`.

what do you think?
Again my tentative is to wrap the local config in a dedicate folder, ideally making also easy and flexible to run a specific one and support multiple modalities.

**Comment by emanuele-leopardi** [comment]
I usually suggest to keep things simple and stupid. I'm not sure there is a simple way to support different methods for local development, so maybe it makes more sense to only chose to support one or two ( in this case either pure npm run, or k8s) 
In either case I wouldn't suggest to over-engineer things.

**Comment by r4m** [comment]
Using Kubernetes for this local server running is over-engineering indeed :smiley: But before stressing out, ok I will accept the pull request since I want to give relevance to your contribution first. I will communicate the release in our Discord too. Thanks @emanuele-leopardi have spent time on providing this alternative local deployment!

**Pull request merged**
